export const hero = {
  brand: "URBANCUT Grooming Studio",
  headline: ["GROOMING,", "ELEVATED."],
  description:
    "Precision barbering and personal grooming in Abuja, at our studio or your location. Professional training through UrbanCut Academy.",
  action: "Book an Appointment",
  bookingNotice: "Appointments requested at least one day ahead",
};
export const heroPhotos = [
  {
    id: 1,
    position: "50% 58%",
    width: 720,
    height: 882,
    alt: "Short textured haircut with a defined hairline and faded sides",
  },
  {
    id: 2,
    position: "50% 52%",
    width: 720,
    height: 806,
    alt: "Close-cropped haircut with a clean line-up, viewed from the side",
  },
  {
    id: 3,
    position: "50% 62%",
    width: 720,
    height: 748,
    alt: "Sectioned twists with a centre part and shaped hairline",
  },
  {
    id: 4,
    position: "50% 50%",
    width: 720,
    height: 813,
    alt: "Locs arranged in clearly defined sections around a centre part",
  },
  {
    id: 5,
    position: "50% 58%",
    width: 720,
    height: 747,
    alt: "Short haircut with a curved shaved part and a shaped beard",
  },
  {
    id: 6,
    position: "50% 45%",
    width: 720,
    height: 825,
    alt: "Child with neatly patterned cornrow braids",
  },
  {
    id: 7,
    position: "50% 48%",
    width: 720,
    height: 960,
    alt: "Short bright red haircut with sunglasses",
  },
  {
    id: 8,
    position: "50% 45%",
    width: 720,
    height: 960,
    alt: "Clean line-up and shaped beard",
  },
  {
    id: 9,
    position: "50% 15%",
    width: 720,
    height: 960,
    alt: "Sharp fade and beard with sunglasses",
  },
  {
    id: 10,
    position: "42% 48%",
    width: 720,
    height: 540,
    alt: "Side view of a textured top and fade",
  },
  {
    id: 11,
    position: "50% 40%",
    width: 720,
    height: 905,
    alt: "Side fade with a heart-shaped shaved detail",
  },
  {
    id: 12,
    position: "50% 50%",
    width: 720,
    height: 960,
    alt: "Side profile of a high textured haircut",
  },
  {
    id: 13,
    position: "50% 40%",
    width: 720,
    height: 961,
    alt: "Waves with a precise faded neckline",
  },
  {
    id: 14,
    position: "50% 50%",
    width: 720,
    height: 960,
    alt: "Braided hair and beard during a clipper finish",
  },
  {
    id: 15,
    position: "50% 66%",
    width: 607,
    height: 1080,
    alt: "Patterned braids viewed from the front",
  },
  {
    id: 16,
    position: "50% 52%",
    width: 720,
    height: 960,
    alt: "Side profile of a close fade with glasses",
  },
  {
    id: 17,
    position: "50% 48%",
    width: 720,
    height: 960,
    alt: "Short waved haircut and shaped hairline",
  },
  {
    id: 18,
    position: "50% 42%",
    width: 720,
    height: 960,
    alt: "Side view of a close fade and defined line-up",
  },
  {
    id: 19,
    position: "50% 50%",
    width: 720,
    height: 960,
    alt: "Centre-parted braids gathered into side sections",
  },
  {
    id: 20,
    position: "55% 50%",
    width: 720,
    height: 900,
    alt: "Defined beard and close haircut viewed from the side",
  },
];
